on: [push, pull_request]

name: Compile for Windows

jobs:
  build:
    name: Build
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
            
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - uses: actions/upload-artifact@v1 
        with:
          name: port_snippet_for_${{ matrix.target }}
          path: target/${{ matrix.target }}/release/port_snippet.exe
