on: [push, pull_request]

name: Compile for Windows

jobs:
  build:
    name: Build
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-gnu
            
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - run: |
          zip --junk-paths binary-${{ matrix.target }} target/${{ matrix.target }}/release/binary{,.exe}
      - uses: actions/upload-artifact@v1
        with:
          name: build-${{ matrix.target }}
          path: binary-${{ matrix.target }}.zip
