on: [push, pull_request]

name: Unit Test

jobs:
  build_and_test:
    name: UnitTest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --release --verbose
